package com.cai.work.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by clarence on 2018/1/12.
 */
@Entity
public class Account {
    @Id
    private long id;
    private String balance;
    private String mobile;
    private String avatarUrl;

    @Generated(31732949)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Account(long id, String balance, String mobile, String avatarUrl) {
        this.id = id;
        this.balance = balance;
        this.mobile = mobile;
        this.avatarUrl = avatarUrl;
    }

    @Generated(882125521)
    public Account() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getBalance() {
        return balance;
    }

    public void setBalance(String balance) {
        this.balance = balance;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }
}
