package com.cai.work.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class Account {
    @Id
    private long id;
    private String mobile;
    private String password;
    private String token;

    @Generated(986309258)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Account(long id, String mobile, String password, String token) {
        this.id = id;
        this.mobile = mobile;
        this.password = password;
        this.token = token;
    }

    @Generated(882125521)
    public Account() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }
}
