package com.cai.work.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

@Entity
public class HomeDataSql {
    @Id
    private long id;
    private String data;

    @Generated(1084894061)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public HomeDataSql(long id, String data) {
        this.id = id;
        this.data = data;
    }

    @Generated(1616088555)
    public HomeDataSql() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
}
