package com.cai.work.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by clarence on 2018/1/12.
 */
@Entity
public class User {
    @Id
    private long id;
    private long user_id;
    private String nickname;
    private String avatar;
    private String phone;
    private int nation_code;
    private String token;


    @Generated(244271224)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public User(long id, long user_id, String nickname, String avatar, String phone,
            int nation_code, String token) {
        this.id = id;
        this.user_id = user_id;
        this.nickname = nickname;
        this.avatar = avatar;
        this.phone = phone;
        this.nation_code = nation_code;
        this.token = token;
    }

    @Generated(586692638)
    public User() {
    }


    public long getUser_id() {
        return user_id;
    }

    public void setUser_id(long user_id) {
        this.user_id = user_id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public int getNation_code() {
        return nation_code;
    }

    public void setNation_code(int nation_code) {
        this.nation_code = nation_code;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
