package com.cai.work.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by clarence on 2018/1/12.
 */
@Entity
public class User {
    @Id
    private long id;
    private String name;

    @Generated(1744782465)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public User(long id, String name) {
        this.id = id;
        this.name = name;
    }

    @Generated(586692638)
    public User() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }
}
