package com.cai.work.bean;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by clarence on 2018/1/12.
 */
@Entity
public class User {
    @Id
    private long id;
    private String balance;
    private String mobile;
    private String avatarUrl;
    private int memberId;
    private int is_withdraw;

    @Generated(2013391937)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public User(long id, String balance, String mobile, String avatarUrl,
            int memberId, int is_withdraw) {
        this.id = id;
        this.balance = balance;
        this.mobile = mobile;
        this.avatarUrl = avatarUrl;
        this.memberId = memberId;
        this.is_withdraw = is_withdraw;
    }

    @Generated(586692638)
    public User() {
    }

    public int getMemberId() {
        return memberId;
    }

    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    public int getIs_withdraw() {
        return is_withdraw;
    }

    public void setIs_withdraw(int is_withdraw) {
        this.is_withdraw = is_withdraw;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getBalance() {
        return balance;
    }

    public void setBalance(String balance) {
        this.balance = balance;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }
}
